apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mbt
  labels:
    app.kubernetes.io/name: mlflow
spec:
  selector:
    app.kubernetes.io/name: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
