apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
  namespace: mbt
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: metabase.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
