apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: mbt
  labels:
    app.kubernetes.io/name: metabase
spec:
  selector:
    app.kubernetes.io/name: metabase
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
